import { Geist, Geist_Mono, Bricolage_Grotesque } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Certiva",
  description:
    "Certiva ensures instant, secure academic credential verification using Starknet and Zero-Knowledge Proofs.Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bricolageGrotesque.variable}`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
} 